repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.56.0
          - typescript@5.3.3
          - eslint-plugin-import@2.29.1
          - eslint-config-prettier@9.1.0
          - "@typescript-eslint/eslint-plugin@6.17.0"
          - "@typescript-eslint/parser@6.17.0"

  - repo: local
    hooks:
      - id: bazel-buildifier
        name: Bazel buildifier
        description: Runs buildifier on Bazel files
        entry: buildifier
        language: system
        files: '(\.bazel$|BUILD$|\.bzl$|WORKSPACE$)'
        exclude: '@.*' 