# Ruff configuration for monorepo Python code
# This extends the settings in pyproject.toml

select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "SIM", # flake8-simplify
    "ERA", # eradicate commented-out code
    "D",   # pydocstyle
    "S",   # flake8-bandit
]

# Moving these to lint.* is recommended but requires more thorough testing
# We'll keep it here for simplicity during initial setup

ignore = [
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D102", # Missing docstring in public method
    "D103", # Missing docstring in public function
    "D104", # Missing docstring in public package
    "D107", # Missing docstring in __init__
    "D202", # No blank lines allowed after function docstring
    "D203", # one-blank-line-before-class - conflicts with D211
    "D213", # multi-line-summary-second-line - conflicts with D212
]

# Exclude a variety of commonly ignored directories
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "bazel-*",
]

# Same as Black
line-length = 88
target-version = "py311"

[pydocstyle]
convention = "google"

[lint.per-file-ignores]
"__init__.py" = ["F401", "D104"]
"**/test_*.py" = ["D100", "D101", "D102", "D103", "S101"]

[lint.mccabe]
max-complexity = 10

[lint.flake8-quotes]
docstring-quotes = "double"

[lint.isort]
known-first-party = ["python"]
known-third-party = ["pytest", "yaml", "pydantic", "typer", "httpx"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"