[tool.ruff]
target-version = "py311"
line-length = 88
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "N",  # pep8-naming
    "UP", # pyupgrade
    "B",  # flake8-bugbear
]
ignore = []

[tool.ruff.isort]
known-first-party = []
known-third-party = []

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]  # unused imports 