name: Python CI Test

on:
  workflow_dispatch:

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest pydantic typer httpx pyyaml
      
      - name: Lint with Ruff
        run: |
          ruff check --exit-zero python/
          ruff format --check python/ || true